---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: gitlabpages
spec:
  ambassador_id: ambassador-web-sys
  prefix: /
  service: http://gitlab-cloudnative-gitlab-pages:8090
  host: ".*\\.pages\\.gitlab\\.payconiq\\.io$"
  host_regex: true
  timeout_ms: 60000

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: gitlab-cloudnative
spec:
  ambassador_id: ambassador-web-sys
  prefix: /
  service: http://gitlab-cloudnative-webservice-default:8181
  host: gitlab.payconiq.io
  timeout_ms: 60000
  cors:
    origins: https://general.pages.gitlab.payconiq.io
    methods: POST, GET, OPTIONS
    headers: Content-Type
    credentials: true
    max_age: "86400"

---
apiVersion: getambassador.io/v2
kind: TCPMapping
metadata:
  name: gitlab-ssh
spec:
  ambassador_id: ambassador-web-sys
  port: 2222
  service: gitlab-cloudnative-gitlab-shell:2222
  idle_timeout_ms: "60000"
