apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab

resources:
- ../../base
- gitlab-application.yaml

patches:
- path: values-patch.yaml
  target:
    kind: HelmChart
    name: gitlab

labels:
- pairs:
    environment: production
    app.kubernetes.io/environment: production

configMapGenerator:
- name: gitlab-config
  behavior: merge
  literals:
    - ENVIRONMENT=production