apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab

helmCharts:
- name: gitlab
  repo: https://charts.gitlab.io
  version: "5.9.5"
  releaseName: gitlab
  valuesFile: values.yaml
  includeCRDs: true

resources:
- namespace.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: gitlab